services:
  backend:
    build: ./backend_server
    ports:
      - "8000:8000"
    env_file:
      - ./backend_server/.env
    volumes:
      - ./backend_server:/app 
      - /app/node_modules
    networks:
      - app_network

  frontend:
    build: ./frontend_skillnova
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend_skillnova:/app
      - /app/node_modules 
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
